##sonarqube default username: admin
##sonarqube default password: admin
version: "2"

services:

  nginx: 
    depends_on:
      - sonarqube
      - db
    image: nginx
    networks:
      - sonarnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #Execute "sudo openssl req -subj '/CN=localhost' -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365" 
      #and put cert.pem, key.pem in the conf.d directory. 
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443

  sonarqube:
    depends_on:
      - db
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar   

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar


networks:
  sonarnet:
    driver: bridge